### Задачи:

Сколько видов ирисов в датасете, какие это виды?

Найти средние и медианы размеры чашелистиков и лепестков для каждого из видов (построить сводную таблицу).

In [1]:
import pandas as pd

In [2]:
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv') # открытие датасета
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# Сколько видов ирисов в датасете, какие это виды?
iris.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

##### В датасете есть три вида ирисов: setosa, versicolor, virginica.

In [4]:
# Средние и медианы размеры чашелистиков и лепестков для каждого из видов.
iris.groupby('species').agg({
    'sepal_length':['mean','median'],# среднее и медиана длины чашелистиков
    'sepal_width':['mean','median'],# среднее и медиана ширины чашелистиков
    'petal_length':['mean','median'],# среднее и медиана длины лепестков
    'petal_width':['mean','median']# среднее и медиана ширины лепестков
})

           sepal_length        sepal_width        petal_length         \
                   mean median        mean median         mean median
species
setosa            5.006    5.0       3.428    3.4        1.462   1.50
versicolor        5.936    5.9       2.770    2.8        4.260   4.35
virginica         6.588    6.5       2.974    3.0        5.552   5.55

           petal_width
                  mean median
species
setosa           0.246    0.2
versicolor       1.326    1.3
virginica        2.026    2.0